### PR TITLE
fix(form-input): properly handle out-of-sync values (closes #2657)

### LINKED ISSUE #2657: <b-form-input> becoming out of sync with value if using formatter
When a form-input has a formatter on it stripping out characters in the case of trying to only allowing numerial values in a text input, the input value can sometimes not match up with the emitted value.

codepen: https://codepen.io/Kalvens/pen/Lqabrj (type any nonnumerical character in the input)
browser: Chrome Version 69.0.3497.100 (Official Build) (64-bit)
OS: linux

I believe the issue comes from 
https://github.com/bootstrap-vue/bootstrap-vue/blob/a14245cc27751e395f34b90fba20db16869a3484/src/mixins/form-text.js#L107-L123

the value is already formatted at that point so if the formatter strips out all of the characters leaving the value to be an empty string, nothing will happen even though the input still has a value set for it

I was playing around with your source code and doing
```javascript
if (this.localValue !== value) {
    ...
} else if (this.$el.value !== value)  {
  this.$el.value = value;
}
```
seems to fix my issue, but I am not sure if that would be affecting anything else using the mixin.

### PR DESCRIPTION
**Pull request by jackmu95**
### Describe the PR

This PR adds an additional check to to the `updateValue()` method to check if the given value is different from the actual input value, even when the `localValue` hasn't changed.
This can be caused by the `formatter` function.

Closes #2657.

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Enhancement
- [ ] ARIA accessibility
- [ ] Documentation update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples, fix typos`, `chore: fix typo in README`, etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates (including updating the component's `package.json` for slot and event changes)
- [ ] New/updated tests are included and passing (if required)
- [ ] Existing test suites are passing
- [ ] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

File: src/mixins/form-text.js [hunk 1]
```diff
@@ -100,38 +100,44 @@ export default {
...
-          // Emulate .trim modifier behaviour
+          // Emulate `.trim` modifier behaviour
           value = value.trim()
         }
         // Update the v-model
         this.$emit('update', value)
+      } else if (value !== this.$refs.input.value) {
+        // When the `localValue` hasn't changed but the actual input value
+        // is out of sync, make sure to change it to the given one
+        this.$refs.input.value = value
```
Comment (tmorehouse) [inline src/mixins/form-text.js]: One thing to note about this is that it can cause the user's cursor/insert point to jump.  Although in general, formatters will have that effect as well.

Comment (jackmu95) [reply src/mixins/form-text.js]: Yeah, I think we can/have to live with that.

Comment (tmorehouse) [reply src/mixins/form-text.js]: May want to add an `/*istanbul ignore next */` above the line, as it will be difficult to test this scenario
