### PR TITLE
fix(tabs): fix regression with dynamically added tabs (fixes #3395)

### LINKED ISSUE #3395: Dynamic b-tab generation doesn't work with fetch call
### Describe the bug

On the created() hook, the result of a fetch call is saved as array of integers in the model. On the view, a v-for creates a b-tab for each element in the array. This was working in 2.0.0-rc.20

### Steps to reproduce the bug

Use Bootstrap-Vue version 2.0.0-rc.21, see demo link.

### Expected behavior

A list of tab should be created on the view after the array is populated.

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc21
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: PC
- OS: Windows 10
- Browser: Chrome
- Version: 74

### Demo link
rc.20 - **Working**
https://jsfiddle.net/jvmp90Ln/
rc.21 - **Not working**
https://jsfiddle.net/n1hbsmpw/

### PR DESCRIPTION
**Pull request by tmorehouse**
### Describe the PR

Fix when using tabs that are dynamically created

Fixes #3395

Other tweaks:
- removed reliance on MutationObserver for detecting new tabs
- `b-tab` instances now notify `b-tabs` when they have been mounted/unmounted, so that `b-tabs` can then update its list of tabs (in DOM order)
- We still need to use DOM queries after mount (in `b-tabs`) to determine tab order and tab VM instances, as `this.$slots.default` may have cached old vnode instances which don't reflect the current instances (might be a 2.6.x Vue bug, or side-effect of new slot handling), when rendered inside lazy modals
  - While `this.$children` does have accurate lists of the `b-tab` instances, unlike `this.$slots.default`, we can't rely on it as the children in `this.$children` are not guaranteed to be in document order.

Discovered that the issue is related to how Vue 2.6.x allows a child to re-render in a parent slot, without triggering the parent to re-render.. by returning the same vNodes array as before. This is the weird effect we are seeing with tabs rendered inside lazy modals.

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Enhancement
- [ ] ARIA accessibility
- [ ] Documentation update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [ ] No
- [ ] Yes (please describe)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [ ] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [ ] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [ ] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples, fix typos`, `chore: fix typo in README`, etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates (including updating the component's `package.json` for slot and event changes)
- [ ] New/updated tests are included and passing (if required)
- [x] Existing test suites are passing
- [x] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

File: src/components/tabs/tabs.js [hunk 1]
```diff
@@ -292,65 +306,58 @@ export default Vue.extend({
...
-        // Make sure no existing observer running
-        this.setObserver(false)
-        // Watch for changes to <b-tab> sub components
-        this._bvObserver = observeDom(this.$refs.tabsContainer, this.updateTabs.bind(this), {
-          childList: true,
-          subtree: false,
-          attributes: true,
-          attributeFilter: ['style', 'class']
+    registerTab(tab) {
+      if (!arrayIncludes(this.registeredTabs)) {
```
Comment (jackmu95) [inline src/components/tabs/tabs.js]: `if (!arrayIncludes(this.registeredTabs, tab)) {`

Comment (tmorehouse) [reply src/components/tabs/tabs.js]: Oops

Comment (tmorehouse) [reply src/components/tabs/tabs.js]: good catch

**Comment by BillSchumacher** [comment]
Someone broke nested tabs, I suspect this is the cause...

**Comment by BillSchumacher** [comment]
@2.0.0-rc.20 nested tabs still work. Also, why is unpkg giving the pre-release version with @latest?

**Comment by tmorehouse** [comment]
It is publishing as `@latest` as it has been for quite a while (2.0.0 has been always been RC, and never when through beta release stages).

2.0.0 stable will hopefully be released soon, and then we can start following semver releases.

2.0.0-rc.22 will be released tonight.
