### PR TITLE
fix(b-link): `href` handling inconsistencies to `<router-link>` (closes #5820)

### LINKED ISSUE #5820: to is not resolved as router-link
### Describe the bug

Here's simple example:

```
<b-link :to="{ name: item.route }" href="http://google.com">Link</b-link>

<router-link :to="{ name: item.route }" href="http://google.com">Link</router-link>
```

In the above two lines of code if `item.route` is `undefined` then `b-link` still resolve the route and give the unexpected route link. Whereas if you use `router-link` then it somehow resolves correctly and give URL of google.com.

### Steps to reproduce the bug

1. Just use above two lines
2. define `item` as empty object so `item.route` return `undefined`

### Expected behavior

Isn't b-link should give link for google if `item.route` is undefined just like `router-link`

### Versions

**Libraries:**

- BootstrapVue: 2.17.3
- Bootstrap: 4.5.2
- Vue: 2.6.12

**Environment:**

- Device: PC
- OS: Linux Mint
- Browser: Chrome
- Version: 85

### PR DESCRIPTION
**Pull request by jackmu95**
### Describe the PR

This PR fixes inconsistencies for the `href` handling between `<b-link>` and `<router-link>`.

Closes #5820.

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix (fixes a boo-boo in the code) - `fix(...)`, requires a patch version update
- [ ] Feature (adds a new feature to BootstrapVue) - `feat(...)`, requires a minor version update
- [ ] Enhancement (augments an existing feature) - `feat(...)`, requires a minor version update
- [ ] ARIA accessibility (fixes or improves ARIA accessibility) - `fix(...)`, requires a patch or minor version update
- [ ] Documentation update (improves documentation or typo fixes) - `chore(docs)`, requires a patch version update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe since breaking changes require a minor version update)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples`, `chore(docs): fix typo in README`, etc.). **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type (patch or minor).**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates
- [ ] Includes component package.json meta section updates (prop, slot and event changes/updates)
- [ ] Includes any needed TypeScript declaration file updates
- [ ] New/updated tests are included and passing (required for new features and enhancements)
- [ ] Existing test suites are passing
- [ ] CodeCov for patch has met target (all changes/updates have been tested)
- [ ] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

File: src/utils/router.js [hunk 1]
```diff
@@ -109,45 +102,26 @@ export const computeTag = ({ to, disabled, routerComponentName } = {}, thisOrPar
...
-export const computeHref = (
-  { href, to } = {},
-  tag = ANCHOR_TAG,
-  fallback = '#',
-  toFallback = '/'
-) => {
-  // We've already checked the $router in computeTag(), so isRouterLink() indicates a live router.
-  // When deferring to Vue Router's router-link, don't use the href attribute at all.
-  // We return null, and then remove href from the attributes passed to router-link
-  if (isRouterLink(tag)) {
```
Comment (jackmu95) [inline src/utils/router.js:128]: @Hiws I've looked up when and why this was added and could track it down to this PR way back in 2017:
https://github.com/bootstrap-vue/bootstrap-vue/issues/1015

I've created a simple demo on CodeSandbox to make sure this still works:
https://codesandbox.io/s/bootstrapvue-starter-project-forked-dihox

**Review by Hiws — APPROVED** [review]
