### PR TITLE
fix(b-nav-item-dropdown): clicking toggle a second time should close menu (closes #3707)

### LINKED ISSUE #3707: <b-nav-item-dropdown>: Flickers when trying to close with click on dropdown
When trying to close navbar dropdown with clicking on dropdown again it just flickers. Events are triggering twice and you can't close dropdown with clicking on dropdown again, you have to click on some dropdown items or out of dropdown.

How to reproduce:
1) Go to https://bootstrap-vue.js.org/docs/components/navbar/#b-nav-item-dropdown
2) Click on "Lang"
3) Click on "Lang" again to close dropdown. (Only flickering happens) 

How it should work:
Like regular dropdown: https://bootstrap-vue.js.org/docs/components/dropdown

### PR DESCRIPTION
**Pull request by tmorehouse**
### Describe the PR

`b-nav-item-dropdown` wasn't closing the menu on second click of the toggler, unlike `b-dropdown`

One Issue was that there was a check for toggle event `defaultPrevented` (native event), and `b-link` when HREF is '#' prevents default to stop scroll to top behaviour, which prevents `b-nav-item-dropdown` from closing the menu.

Removed the check for `defaultPrevented` in dropdown mixin.

The other issue was that `focusInHandler()` used `this.$refs.toggle` to check wether the event target is contained. `this.$refs.toggle` can be a component in some places. Using the computed `toggler` property for the check solved the problem.

Closes #3707.

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Enhancement
- [ ] ARIA accessibility
- [ ] Documentation update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples, fix typos`, `chore: fix typo in README`, etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates (including updating the component's `package.json` for slot and event changes)
- [x] New/updated tests are included and passing (if required)
- [x] Existing test suites are passing
- [x] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

File: src/components/nav/nav-item-dropdown.js [hunk 1]
```diff
@@ -56,7 +56,6 @@ export const BNavItemDropdown = /*#__PURE__*/ Vue.extend({
         this.extraToggleClasses, // Deprecated
         this.toggleClass,
         {
-          disabled: this.disabled,
```
Comment (jackmu95) [inline src/components/nav/nav-item-dropdown.js]: @tmorehouse Why was this disabled class removed?

Comment (tmorehouse) [reply src/components/nav/nav-item-dropdown.js]: BLink adds the disabled class automatically
