### PR TITLE
fix(v-b-toggle): prevent scroll anchoring behavior (closes #5715)

### LINKED ISSUE #5715: <b-collapse> Accordion causes page to scroll
### Describe the bug

Since Chromium 84, the page scrolls with the toggle button of an accordion (might be other scenarios), because the browser tries to keep the button in the same position in the viewport.

This has been fixed in Bootstrap `4.5.1` via this PR: https://github.com/twbs/bootstrap/pull/31347
However, because Bootstrap-Vue doesn't follow the same structure for accordions it doesn't apply here.

The fix is to add the style `overflow-anchor: none` to either the toggle button or a parent of the button.

We could solve this by adding a `overflow-anchor-none` and `overflow-anchor-visible` utility classes, and have `overflow-anchor-none` applied by default via `v-b-toggle`, and for users toggling accordion's another way could still utilize the helper class  to turn off the behavior if they want.

Maybe have a setting to decide whether `v-b-toggle` should turn off this behavior or not.

### Steps to reproduce the bug

1. Go to https://bootstrap-vue.org/docs/components/collapse#accordion-support
2. Open a accordion *under* an accordion which is already open
3. The browser should scroll the window up, keeping the clicked button in the same position in the viewport

### Versions

**Libraries:**

- BootstrapVue: 2.16.0
- Bootstrap: 4.5.2
- Vue: 2.6.11

**Environment:**

- OS: Windows
- Browser: Chromium (Chrome, Edge..)
- Version: 84+

### PR DESCRIPTION
**Pull request by jackmu95**
### Describe the PR

This PR prevents the browsers scroll anchoring behavior when using `v-b-toggle` with the `<b-collapse>` component as a `accordion` by setting the `overflow-anchor` style property to  `none`.

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix (fixes a boo-boo in the code) - `fix(...)`, requires a patch version update
- [ ] Feature (adds a new feature to BootstrapVue) - `feat(...)`, requires a minor version update
- [ ] Enhancement (augments an existing feature) - `feat(...)`, requires a minor version update
- [ ] ARIA accessibility (fixes or improves ARIA accessibility) - `fix(...)`, requires a patch or minor version update
- [ ] Documentation update (improves documentation or typo fixes) - `chore(docs)`, requires a patch version update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe since breaking changes require a minor version update)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples`, `chore(docs): fix typo in README`, etc.). **This is very important, as the `CHANGELOG` is generated from these messages, and determines the next version type (patch or minor).**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates
- [ ] Includes component package.json meta section updates (prop, slot and event changes/updates)
- [ ] Includes any needed TypeScript declaration file updates
- [ ] New/updated tests are included and passing (required for new features and enhancements)
- [ ] Existing test suites are passing
- [ ] CodeCov for patch has met target (all changes/updates have been tested)
- [ ] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

File: src/components/form-textarea/form-textarea.js [hunk 1]
```diff
@@ -171,13 +171,13 @@ export const BFormTextarea = /*#__PURE__*/ Vue.extend({
       const minHeight = lineHeight * this.computedMinRows + offset
 
       // Get the current style height (with `px` units)
-      const oldHeight = el.style.height || computedStyle.height
+      const oldHeight = getStyle(el, 'height') || computedStyle.height
       // Probe scrollHeight by temporarily changing the height to `auto`
-      el.style.height = 'auto'
+      setStyle(el, 'auto')
```
Comment (Hiws) [inline src/components/form-textarea/form-textarea.js:176]: Should this be `setStyle(el, 'height', 'auto')`?

Same case at line 180

Comment (jackmu95) [reply src/components/form-textarea/form-textarea.js:176]: Good catch!
