### PR TITLE
fix(b-form-textarea): handle initial auto-height when in modal, tabs, or other component with transition or which uses `v-show` (fixes #3936, #3702)

### LINKED ISSUE #3702: Auto-height b-form-textarea within a b-tab does not work
When b-form-textarea is contained within a b-tab that is not initially active, the auto-height feature does not work. In the following code, Tab 1 - the initially active tab, works and the textarea is automatically resized, Tab 2 however does not resize the textarea when clicked.

This can be fixed by calling setHeight() on the b-textarea component when the tab changes but this is not a published API method and resize should occur automatically.

Vue:
```
    <b-tabs>
      <b-tab title="Tab 1" active>
        <b-form-group label="Tab 1 Notes" label-size="sm" label-cols="3" horizontal>
          <b-form-textarea ref="tab1Notes" size="sm" max-rows="15" v-model="tab1Notes"></b-form-textarea>
        </b-form-group>
      </b-tab>
      <b-tab title="Tab 2">
        <b-form-group label="Tab 2 Notes" label-size="sm" label-cols="3" horizontal>
          <b-form-textarea ref="tab2Notes" size="sm" max-rows="15" v-model="tab2Notes"></b-form-textarea>
        </b-form-group>
      </b-tab>
    </b-tabs>

```
JS:
```
import Vue from 'vue';

var indexVm = new Vue({

    el: '#testbed-app',

    data() {
        return {
            tab1Notes: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris viverra leo eget auctor imperdiet. Aliquam interdum tellus in urna sollicitudin mollis.\
            Aenean consectetur justo sit amet efficitur luctus. Maecenas posuere magna neque, nec ultricies diam aliquam ac. Sed venenatis bibendum sapien ut fringilla. \
            Maecenas pulvinar erat eget urna ultricies, non consectetur erat eleifend. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; \
            Curabitur lorem nulla, placerat sed ullamcorper et, fermentum nec ipsum. Proin efficitur ipsum sit amet elit posuere vehicula nec at quam. \
            Nulla facilisi. Nunc libero orci, commodo quis nibh eu, porttitor imperdiet dui. Donec mollis suscipit malesuada. Aliquam porta rhoncus nisi, vel volutpat arcu rhoncus sed. \
            Praesent ultrices ligula eu luctus porta. Pellentesque ipsum purus, tempor a eleifend quis, eleifend ut nisl.\
            \
            Ut pulvinar tristique odio et commodo. Praesent ac lorem sapien. Curabitur ut orci ac ante ornare bibendum vel a justo. Nunc sed diam nec urna tristique blandit hendrerit sed dui. \
            Maecenas tempus, velit et convallis tincidunt, mi odio luctus ipsum, eget ullamcorper nunc nulla sit amet eros. Proin ultricies molestie massa, sit amet tincidunt lacus elementum a. Donec id commodo justo.',

            tab2Notes: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras faucibus elit eu velit dapibus imperdiet. \
            Aliquam ut accumsan lorem. Vestibulum ut risus sollicitudin, convallis purus non, sollicitudin velit. \
            Aliquam sapien eros, sagittis vitae ornare vitae, dignissim eu arcu. Integer vehicula massa lectus, molestie accumsan ipsum malesuada eu. Integer ut nibh mollis nulla dignissim scelerisque. \
            Sed vitae diam semper, egestas mauris vel, ultrices dui. Suspendisse quis gravida nibh. Donec pellentesque condimentum blandit. \
            Proin porttitor risus lacus, sit amet facilisis sem commodo non. Nam laoreet tempus quam non efficitur. In eu accumsan nulla. Donec eu tincidunt nibh, quis lobortis nisl.'
        };
    },
    
    mounted: function() {
    },
    
    methods: {
    }
});

```

### LINKED ISSUE #3936: Hidden `b-form-textarea` not auto-sizing when becoming viable
### Describe the bug

When a textarea is initially hidden it isn't rendered correctly.
The rows property is not taken into account, so the textarea is very small.

### Steps to reproduce the bug

1. Put a b-form-textarea inside a modal
2. Open the modal
3. The textarea has not the correct height
4. Type in something and it automatically adjust its height

### Expected behavior

The textarea should have the correct height from the beginning

Before
before

After typing in a character
after

### Versions

**Libraries:**

- BootstrapVue: 2.0.0-rc.28
- Bootstrap: 4.3.1
- Vue: 2.6.10

**Environment:**

- Device: Mac
- OS: macOS Mojave
- Browser: Chrome
- Version: 76

### PR DESCRIPTION
**Pull request by tmorehouse**
### Describe the PR

Incorporates `IntersectionObserver` for visibility checks and runs the height computation when the textarea becomes visible.  Useful when the component is inside a non-lazy modal or b-tab component.  Handles situations where the textarea is hidden via `display: none` (i.e. `v-show`)

Fixes issues with the initial auto-resize when placed inside modals, b-tabs, etc, or an element/component that has the directive `v-show` on it.

The visibility observer is implemented as a private directive. The directive does nothing if `IntersectinObserver` is not available (either natively or via polyfill). IE11 requires a polyfill for `IntersectinObserver`.

Fixes #3936
Fixes #3702

Future (after merging): update the following components to use the new private visibility directive:
- `b-img-lazy` (to determine when image is in viewport),
- `b-carousel` (for pausing cycling when not visible),
- `form-*` controls which have the autofocus prop

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [x] Enhancement
- [ ] ARIA accessibility
- [x] Documentation update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples, fix typos`, `chore: fix typo in README`, etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [x] Includes documentation updates (including updating the component's `package.json` for slot and event changes)
- [ ] Includes any needed TypeScript declaration file updates
- [x] New/updated tests are included and passing (if required)
- [x] Existing test suites are passing
- [x] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

File: src/components/form-textarea/form-textarea.js [hunk 1]
```diff
@@ -1,19 +1,25 @@
 import Vue from '../../utils/vue'
+import VBVisible from '../../utils/vb-visible'
```
Comment (jackmu95) [inline src/components/form-textarea/form-textarea.js]: Maybe we should move this to a separate `directives` directory like we do with `mixins`.

Comment (tmorehouse) [reply src/components/form-textarea/form-textarea.js]: We have a directives dir (for public directives), but only certain directives are published in the docs... so yeah, this could move there maybe.

Comment (jackmu95) [reply src/components/form-textarea/form-textarea.js]: Yeah, that sounds like a good idea.

Comment (tmorehouse) [reply src/components/form-textarea/form-textarea.js]: Changed.
