### PR TITLE
fix(router-link): remove default values for active-class and exact-active-class (Fixes #2387)

### LINKED ISSUE #2387: bug[b-link]: Global active-class and exact-active-class overridden by prop defaults
When a global `active-class` and `exact-active-class` are defined in `vue-router` or `nuxt.js`, `<b-link>` (and all components that inherit from `<b-link>`) is overriding these by specifically defaulting the props to the Bootstrap V4 class `active`.

Related issue #1967 

Changing the props to default to `undefined` would remedy this, but might be constituted as a breaking change

### PR DESCRIPTION
**Pull request by tmorehouse**
## Description of Pull Request:

Removes the default values (setting to `undefined`) for props `active-class` and `exact-active-class`, so that the globally configured values can be used by default.

Affects `b-link`, `b-button`, `b-dropdown-item` and other components that build on `b-link` (i.e. have a `to` prop).

Fixes #2387, #1967

## PR checklist:

**What kind of change does this PR introduce?** (check at least one)
- [x] Bugfix
- [ ] Feature
- [ ] Enhancement to an existing feature
- [ ] ARIA accessibility
- [ ] Documentation update
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)
- [x] Yes
- [ ] No

Components that accept a `to` prop will no longer default to using `active` as the class when the router-link is in the active state, but will instead use the globally configured values from vue-router (or nuxt) if the props `active-class` and `exact-active-class` are not set.

**While this change does not affect functionality of the component(s), it _may affect_ the appearance if the user has not provided values to the props.**

**The PR fulfills these requirements:**
- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e. `fixes #xxxx[,#xxxx]`, where "xxxx" is the issue number)
- [x] The PR should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] PR titles should following the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. "fix(alert): not alerting during SSR render", "docs(badge): Updated pill examples, fix typos", "chore: fix typo in docs", etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

**If new features/enhancement/fixes are added or changed:**
- [ ] Includes documentation updates (including updating the component's `package.json` for slot and event changes)
- [ ] New/updated tests are included and passing (if required)
- [x] Existing test suites are passing
- [x] The changes have not impacted the functionality of other components or directives 
- [ ] ARIA Accessibility has been taken into consideration (does it affect screen reader users or keyboard only users? clickable items should be in the tab index, etc)

**If adding a new feature, or changing the functionality of an existing feature, the PR's description above includes:**
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

File: docs/components/nav.vue [hunk 1]
```diff
@@ -60,9 +60,6 @@
           right>
           <b-dropdown-item href="http://dev.bootstrap-vue.netlify.com">Development</b-dropdown-item>
```
Comment (jackmu95) [inline docs/components/nav.vue]: Shouldn't we use `https://` here because there is a redirect anyway.
A SSL cert for this subdomain would be ideal.

Comment (tmorehouse) [reply docs/components/nav.vue]: Yeah, although I don't believe this link actually works atm, and will need to be updated before release.
