### PR TITLE
fix(table): don't emit row/head-clicked when user is selecting text (Closes #2791)

### LINKED ISSUE #2791: Question: table row-click vs select text within the row
I would like to select text in a table row that has @row-clicked enabled.

After I release the mouse after selecting the text, the @row-clicked event triggered.  Is there an easy way to distinguish the mouse up event that's from a mouse click vs selecting text (somehow a mouse move event disable the click event)

### PR DESCRIPTION
**Pull request by tmorehouse**
## Description of Pull Request:

When user is selecting a range of text in the table, a row-clicked event was occurring.

This PR filters out click events when the user is in the midst of composing a text selection.

closes #2791

## PR checklist:

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [x] Enhancement to an existing feature
- [ ] ARIA accessibility
- [ ] Documentation update
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e.
      `fixes #xxxx[,#xxxx]`, where "xxxx" is the issue number)
- [x] The PR should address only one issue or feature. If adding multiple features or fixing a bug
      and adding a new feature, break them into separate PRs if at all possible.
- [x] PR titles should following the
      [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e.
      "fix(alert): not alerting during SSR render", "docs(badge): Updated pill examples, fix typos",
      "chore: fix typo in docs", etc). **This is very important, as the `CHANGELOG` is generated
      from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates (including updating the component's `package.json` for slot and
      event changes)
- [ ] New/updated tests are included and passing (if required)
- [x] Existing test suites are passing
- [x] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (does it affect screen reader users or
      keyboard only users? clickable items should be in the tab index, etc)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a
      suggestion issue first and wait for approval before working on it)

### CODE REVIEW

File: src/components/table/table.js [hunk 1]
```diff
@@ -919,12 +919,17 @@ export default {
     },
     // Event handlers
     rowClicked(e, item, index) {
+      const getSelection = (document || {}).getSelection || (window || {}).getSelection
```
Comment (jackmu95) [inline src/components/table/table.js]: Maybe we should create a util for that. Something like:
```js
const getSelection = () => {
  if (document.getSelection) {
    return document.getSelection()
  }
  if (window.getSelection) {
    return window.getSelection()
  }
  return null
}
```

Comment (tmorehouse) [reply src/components/table/table.js]: Yeah, thought about that, but not sure if we would be using it anywhere else.

Comment (tmorehouse) [reply src/components/table/table.js]: Moved to a top of file helper function, as it is used for both `row-clicked` and `head-clicked` events.
