### PR TITLE
fix(utils): Make `looseEqual()` util handle File's comparison correctly

### LINKED ISSUE #2638: b-form-file: model doesn't change if another file is selected
When changing the selected file, the model isn't updated and still contains the first selected file.

On https://bootstrap-vue.js.org/docs/components/form-file/ 
First, select a file and notice how the "Selected file:" text now shows the selected filename. Then, select another file. The "Selected file:" text doesn't change and still shows the first filename. I would expect the newly selected filename to be shown here.

Tested on Firefox 65.0, Bootstrap version bootstrap-vue@eb07b196f3762

### PR DESCRIPTION
**Pull request by jackmu95**
## Description of Pull Request:

This PR fixes a bug in the `looseEqual()` util that returned `true` if two [File](https://developer.mozilla.org/de/docs/Web/API/File) objects were passed because `Object.keys()` returns an empty array.

Closes #2638.

## PR checklist:

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Enhancement to an existing feature
- [ ] ARIA accessibility
- [ ] Documentation update
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e.
      `fixes #xxxx[,#xxxx]`, where "xxxx" is the issue number)
- [x] The PR should address only one issue or feature. If adding multiple features or fixing a bug
      and adding a new feature, break them into separate PRs if at all possible.
- [x] PR titles should following the
      [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e.
      "fix(alert): not alerting during SSR render", "docs(badge): Updated pill examples, fix typos",
      "chore: fix typo in docs", etc). **This is very important, as the `CHANGELOG` is generated
      from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates (including updating the component's `package.json` for slot and
      event changes)
- [ ] New/updated tests are included and passing (if required)
- [ ] Existing test suites are passing
- [ ] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (does it affect screen reader users or
      keyboard only users? clickable items should be in the tab index, etc)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a
      suggestion issue first and wait for approval before working on it)

### CODE REVIEW

File: src/utils/loose-equal.js [hunk 1]
```diff
@@ -16,44 +19,27 @@ function isObject(obj) {
...
-        )
-      } else {
-        /* istanbul ignore next */
+  if (a === b) {
+    return true
+  }
+  if (isObject(a) && isObject(b)) {
+    // Using for loop over `Object.keys()` here since some class
+    // keys are not handled correctly otherwise
+    for (const key in a) {
```
Comment (tmorehouse) [inline src/utils/loose-equal.js]: Should we not do a quick comparison of the number of keys in each object for speed?

i.e. the original Vue version did a quick check on `Object.keys(a).length !== Object.keys(b).length` and returned `false` if not equal.

Comment (tmorehouse) [reply src/utils/loose-equal.js]: i.e. if we had the following two objects with the same shape, esxcept for one additional key in the b object:

```js
const a = { a: 1, b: 2, c: 3 }
const b = { a: 1, b: 2, c: 3, d: 4 }
```

Comment (jackmu95) [reply src/utils/loose-equal.js]: We can do that before the for loop for sure.

File: src/utils/loose-equal.js [hunk 2]
```diff
@@ -16,44 +19,27 @@ function isObject(obj) {
...
+      const bHasKey = b.hasOwnProperty(key)
+      if ((aHasKey && !bHasKey) || (!aHasKey && bHasKey) || !looseEqual(a[key], b[key])) {
         return false
       }
-    } catch (e) {
-      /* istanbul ignore next */
-      return false
     }
-  } else if (!isObjectA && !isObjectB) {
-    return String(a) === String(b)
```
Comment (tmorehouse) [inline src/utils/loose-equal.js]: We may want to add this before the last `return false` as a catch all comparison.

Comment (jackmu95) [reply src/utils/loose-equal.js]: Which exact case should this handle?

Comment (jackmu95) [reply src/utils/loose-equal.js]: When there is a case for it we can simply replace the last `return false` with `return String(a) === String(b)`.

Comment (tmorehouse) [reply src/utils/loose-equal.js]: Possibly a custom object/class/etc that may have a toString method. Vue placed it in their original code for some reason.

Comment (tmorehouse) [reply src/utils/loose-equal.js]: Yeah, that may work.

We might want to add in a test spec for this util (based on the tests that Vue has for their version of `looseEqual()`

Comment (jackmu95) [reply src/utils/loose-equal.js]: Yeah. Still not sure about the need of the `String(a) === String(b)`.

**Comment by tmorehouse** [comment]
Just wondering if we just added in a test to see if the object is a file object, and then comparing equality (`===`) between the objects, similar to how the test for Date objects was done, and leave the rest of the code the same as the original Vue `looseEqual` code?  Just to ensure that it works the same as Vue's (except for the additional test for File object instance)?  Since looseEqual is used in many of the form components and others.

**Comment by tmorehouse** [comment]
i.e.:

```js
function looseEqual(a, b) {
  if (a === b) return true
  const isObjectA = isObject(a)
  const isObjectB = isObject(b)
  if (isObjectA && isObjectB) {
    try {
      const isArrayA = isArray(a)
      const isArrayB = isArray(b)
      if (isArrayA && isArrayB) {
        return (
          a.length === b.length &&
          a.every((e, i) => {
            return looseEqual(e, b[i])
          })
        )
      } else if (a instanceof File && b instanceof File) {
        return a === b
      } else if (a instanceof Date && b instanceof Date) {
        return a.getTime() === b.getTime()
      } else if (!isArrayA && !isArrayB) {
        const keysA = keys(a)
        const keysB = keys(b)
        return (
          keysA.length === keysB.length &&
          keysA.every(key => {
            return looseEqual(a[key], b[key])
          })
        )
      } else {
        /* istanbul ignore next */
        return false
      }
    } catch (e) {
      /* istanbul ignore next */
      return false
    }
  } else if (!isObjectA && !isObjectB) {
    return String(a) === String(b)
  } else {
    return false
  }
}
```

**Comment by jackmu95** [comment]
But I'am not sure if File objects are the only case where the current implementation makes problems. I'am going to create some unit tests to back this all up and then we can create a PR for Vue.

File: src/utils/loose-equal.spec.js [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+    const obj2 = { foo: 'bar1' }
+    const nestedObj1 = { ...obj1, bar: [{ ...obj1 }, { ...obj1 }] }
+    const nestedObj2 = { ...obj1, bar: [{ ...obj1 }, { ...obj2 }] }
+    expect(looseEqual(obj1, obj1)).toBe(true)
+    expect(looseEqual(obj1, { ...obj1 })).toBe(false)
+    expect(looseEqual(obj1, obj2)).toBe(false)
+    expect(looseEqual(nestedObj1, nestedObj1)).toBe(true)
+    expect(looseEqual(nestedObj1, { ...nestedObj1 })).toBe(false)
+    expect(looseEqual(nestedObj1, nestedObj2)).toBe(false)
+  })
```
Comment (tmorehouse) [inline src/utils/loose-equal.spec.js]: Maybe a test for objects defined with different key orders (as key order is typically retained in the order they were defined):

```js
const obj3 = { a: 1, b: 2, c: 3 }
const obj4 = { b: 2, c: 3, a: 1 }
expect(looseEuqal(obj3, obj4)).toBe(true)
```

File: src/utils/loose-equal.js [hunk 4]
```diff
@@ -16,44 +20,31 @@ function isObject(obj) {
...
+      return false
+    }
+
+    // Using for loop over `Object.keys()` here since some class
+    // keys are not handled correctly otherwise
+    for (const key in a) {
+      const aHasKey = a.hasOwnProperty(key)
+      const bHasKey = b.hasOwnProperty(key)
+      if ((aHasKey && !bHasKey) || (!aHasKey && bHasKey) || !looseEqual(a[key], b[key])) {
         return false
```
Comment (tmorehouse) [inline src/utils/loose-equal.js]: This should be:
```js
   return (aHasKey && !bHasKey) || (!aHasKey && bHasKey) || !looseEqual(a[key], b[key])
```

As the test for object with same key/values but in different order fails.

File: src/utils/loose-equal.js [hunk 5]
```diff
@@ -16,44 +20,31 @@ function isObject(obj) {
...
       }
-    } catch (e) {
-      /* istanbul ignore next */
-      return false
     }
```
Comment (tmorehouse) [inline src/utils/loose-equal.js]: Should probably return `true` after the for loop.

File: src/utils/loose-equal.js [hunk 6]
```diff
@@ -16,44 +20,31 @@ function isObject(obj) {
...
-  } else if (!isObjectA && !isObjectB) {
-    return String(a) === String(b)
-  } else {
-    return false
   }
+  if (isArray(a) && isArray(b)) {
```
Comment (tmorehouse) [inline src/utils/loose-equal.js]: These two ifs will never be called, since testing for isObject excludes arrays and dates

File: src/utils/loose-equal.js (hunk 4 above)
Comment (tmorehouse) [inline src/utils/loose-equal.js]: Since this returns false, and the fallback at the end returns false, object equality (loose) will not return `true` reliably when two objects have the same shape (but different key orders).

File: src/utils/loose-equal.js [hunk 7]
```diff
@@ -28,39 +28,35 @@ function looseEqual(a, b) {
...
+      : false
   }
-  if (isArray(a) && isArray(b)) {
-    return a.length === b.length && a.every((e, i) => looseEqual(e, b[i]))
-  }
-  if (isObject(a) && isObject(b)) {
-    if (keys(a).length !== keys(b).length) {
+  const validObjectsCount = [isObject(a), isObject(b)].filter(v => v === true).length
+  if (validObjectsCount > 1) {
+    if (validObjectsCount === 1 || keys(a).length !== keys(b).length) {
```
Comment (tmorehouse) [inline src/utils/loose-equal.js]: `validObjectsCount === 1` will never be true as the wrapping if is ` validObjectsCount > 1`

File: src/utils/loose-equal.js [hunk 8]
```diff
@@ -28,39 +28,35 @@ function looseEqual(a, b) {
   if (a === b) {
     return true
   }
-  if (typeof a !== typeof b) {
```
Comment (tmorehouse) [inline src/utils/loose-equal.js]: This would still be a quick bail if the types are different

File: src/utils/loose-equal.js [hunk 9]
```diff
@@ -29,21 +29,21 @@ function looseEqual(a, b) {
     return true
   }
   const validDatesCount = [isDate(a), isDate(b)].filter(Boolean).length
-  if (validDatesCount > 1) {
+  if (validDatesCount > 0) {
```
Comment (tmorehouse) [inline src/utils/loose-equal.js]: could this just be `if (validDatesCount) {`

And wondering if we should use a `let validCount` to re-use the same var to prevent a new stack entry for each `const`?

Comment (jackmu95) [reply src/utils/loose-equal.js]: 1. Don't like that loose checks
2. 👍

File: src/utils/loose-equal.js [hunk 10]
```diff
@@ -31,30 +31,32 @@ function looseEqual(a, b) {
...
   }
-  const validArraysCount = [isArray(a), isArray(b)].filter(Boolean).length
-  if (validArraysCount > 0) {
-    return validArraysCount === 2
+  validTypesCount = [isArray(a), isArray(b)].filter(Boolean).length
+  if (validTypesCount > 0) {
+    return validTypesCount === 2
       ? a.length === b.length && a.every((e, i) => looseEqual(e, b[i]))
       : false
   }
```
Comment (tmorehouse) [inline src/utils/loose-equal.js]: Could this just be:
```js
  if (validTypesCount === 2) {
    return a.length === b.length && a.every((e, i) => looseEqual(e, b[i]))
  }
```
and change all the `if`'s to `else if`? and let the final return false kick in?

Comment (tmorehouse) [reply src/utils/loose-equal.js]: Err... never mind....

Would need to move the computation of the validTypesCount into the if condition

File: src/utils/loose-equal.js [hunk 11]
```diff
@@ -16,44 +25,52 @@ function isObject(obj) {
...
+      return false
+    }
+    if (aKeysCount === 0 && bKeysCount === 0) {
+      return String(a) === String(b)
+    }
+    // Using for loop over `Object.keys()` here since some class
+    // keys are not handled correctly otherwise
+    for (const key in a) {
+      if (
+        [a.hasOwnProperty(key), b.hasOwnProperty(key)].filter(Boolean).length === 1 ||
```
Comment (tmorehouse) [inline src/utils/loose-equal.js]: Since we know `a` will have `key`, can we just check to see if `b` doesn't have the `key`?

Comment (jackmu95) [reply src/utils/loose-equal.js]: I think this is the safest and shortest way to handle this.

Comment (tmorehouse) [reply src/utils/loose-equal.js]: ie:
```js
if ( !b.hasOwnProperty(key) || !looseEqual(a[key], b[key])) {
  return false
}
```

Comment (jackmu95) [reply src/utils/loose-equal.js]: The `a.hasOwnProperty(key)` check is also required in the for loop.

Comment (tmorehouse) [reply src/utils/loose-equal.js]: ok
