### PR TITLE
fix(b-col): handle bool style prop for sm,md,lg,xl

### LINKED ISSUE #1041: Column breakpoint classes without size not working
It's currently not possible to apply the `col-[sm|md|lg|xl]`class without any size.

As an live example look at the [Docs](https://bootstrap-vue.js.org/docs/layout/#stacked-to-horizontal) where the `col-sm` class isn't added to the column.

**Expected**
```vue
<!-- Vue.js template -->
<b-container>
    <b-row>
        <b-col sm>col-sm</b-col>
        <b-col sm>col-sm</b-col>
        <b-col sm>col-sm</b-col>
    </b-row>
</b-container>

<!-- HTML output -->
<div class="container">
  <div class="row">
    <div class="col-sm">col-sm</div>
    <div class="col-sm">col-sm</div>
    <div class="col-sm">col-sm</div>
  </div>
</div>
```

**Currently**
```vue
<!-- Vue.js template -->
<b-container>
    <b-row>
        <b-col sm>col-sm</b-col>
        <b-col sm>col-sm</b-col>
        <b-col sm>col-sm</b-col>
    </b-row>
</b-container>

<!-- HTML output -->
<div class="container">
  <div class="row">
    <div class="col">col-sm</div>
    <div class="col">col-sm</div>
    <div class="col">col-sm</div>
  </div>
</div>
```

### PR DESCRIPTION
**Pull request by alexsasharegan**
Fixes #1041

### CODE REVIEW

File: lib/components/col.js [hunk 1]
```diff
@@ -24,13 +24,18 @@ function strNum() {
...
+    }
     if (breakpoint) {
         className += `-${breakpoint}`;
     }
-    // Handle boolean style prop.
-    if (val === true) {
+    // Handling the boolean style prop when accepting [Boolean, String, Number]
+    // means Vue will not convert <b-col sm /> to sm: true for us.
+    // Since the default is false, an empty string indicates the prop's presence.
+    if (type === "col" && (val === "" || val === true)) {
```
Comment (tmorehouse) [inline lib/components/col.js]: 👍

**Comment by jackmu95** [comment]
@alexsasharegan Looks good to me!
