### PR TITLE
fix(dropdown): focus-out handling when new focus comes from another `dropdown-toggle` (closes #4113)

### LINKED ISSUE #4113: unexpected nav-item-dropdown opening behavior in vertical navbar
### Describe the bug

It's not possible to open a nav-bar dropdown with relatively positioned content items, when another nav-bar dropdown, above the targeted dropdown, is already open.

demo

### Steps to reproduce the bug

1. Go to https://jsfiddle.net/28dr50bk/
2. Click on "Lang"
3. Try to click on "User"

### Expected behavior

The "User" dropdown opens.

### Versions

**Libraries:**

- BootstrapVue: 2.0.1
- Bootstrap: 4.#.#
- Vue: 2.#.#

**Environment:**

- Device: All devices
- OS: macOS Mojave
- Browser: Firefox 69

### Demo link

https://jsfiddle.net/28dr50bk/

### Additional context

This works as intended in native bootstrap.

### PR DESCRIPTION
**Pull request by jackmu95**
### Describe the PR

This PR fixes the `<b-dropdown>` and `<b-nav-item-dropdown>` (when vertical and inline menu is displayed) close handling when focus is lost by clicking an item below, and the item's click handler not firing due to the position of the item moving before the click handler gets a chance to be triggered.

Uses a setTimeout delay to postpone the drop down menu collapse (when in a navbar) when the menu looses focus.

Closes #4113.

### PR checklist

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Enhancement
- [ ] ARIA accessibility
- [ ] Documentation update
- [ ] Other (please describe)

**Does this PR introduce a breaking change?** (check one)

- [x] No
- [ ] Yes (please describe)

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e. `[...] (fixes #xxx[,#xxx])`, where "xxx" is the issue number)
- [x] It should address only one issue or feature. If adding multiple features or fixing a bug and adding a new feature, break them into separate PRs if at all possible.
- [x] The title should follow the [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e. `fix(alert): not alerting during SSR render`, `docs(badge): update pill examples, fix typos`, `chore: fix typo in README`, etc). **This is very important, as the `CHANGELOG` is generated from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates (including updating the component's `package.json` for slot and event changes)
- [ ] Includes any needed TypeScript declaration file updates
- [x] New/updated tests are included and passing (if required)
- [x] Existing test suites are passing
- [x] The changes have not impacted the functionality of other components or directives
- [x] ARIA Accessibility has been taken into consideration (Does it affect screen reader users or keyboard only users? Clickable items should be in the tab index, etc.)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

### CODE REVIEW

File: src/mixins/dropdown.js [hunk 1]
```diff
@@ -379,7 +379,12 @@ export default {
     focusInHandler(evt) {
       const target = evt.target
       // If focus leaves dropdown, hide it
-      if (this.visible && !contains(this.$refs.menu, target) && !contains(this.toggler, target)) {
+      if (
+        this.visible &&
+        !contains(this.$refs.menu, target) &&
+        !contains(this.toggler, target) &&
+        !hasClass(target, 'dropdown-toggle')
```
Comment (tmorehouse) [inline src/mixins/dropdown.js]: The only issue with this, is when keyboard-only users tab to a dropdown toggle button, hit eneter to "click" the menu open, then tab through the items in the menu until they get to the next tabable on the screen (which is another dropdown toggle).  The menu stays open and obscures the button (I've pushed the top dropdown toggle over a a bit to show the dropdown toggle below it that is obscured):

image


To works fine if users are clicking, but not if using tabs to navigate to the next dropdown.

We might need to add in additional checks, or maybe figure out why the trigger is not opening the next menu (in the original issue)

I

Comment (jackmu95) [reply src/mixins/dropdown.js]: Good catch

Comment (tmorehouse) [reply src/mixins/dropdown.js]: Otherwise, it was working OK to fix the original issue.

Comment (tmorehouse) [reply src/mixins/dropdown.js]: It might be a timing issue with the dropdowns and listening/emitting events (which cause the dropdown to close if another is open), or something similar.

Comment (jackmu95) [reply src/mixins/dropdown.js]: @tmorehouse Yeah, I think so too.

Comment (tmorehouse) [reply src/mixins/dropdown.js]: Maybe we may need to add in a bunch of console log debug statements in each event handler of dropdown mixin, just to see what sequence of events is preventing the second dropdown in the vertical navbar from opneing when the first one is closed.

Or perhaps it is related to the `display` being flex-column in the original issue markup...

May need to nextTick delay a few things or use requestAF to delay a few things (to make sure the transition is completed)

Comment (tmorehouse) [reply src/mixins/dropdown.js]: Hmmmm

Something interesting:

- Go to the fiddle: https://jsfiddle.net/28dr50bk/
- Click on "User" dropdown toggle to open it.
- Then click on "Lang" dropdown toggle to open it

Everything works as expected...

But click on "User" first, then "Lang" then the issue happens.

Comment (tmorehouse) [reply src/mixins/dropdown.js]: What is one simply wraps the following line `this.visible = false` in a `$nextTick()`?

I think what is happening is that the toggle button is moving (because the top dropdown is collapsing), and is not really what was clicked to close the first dropdown?

Comment (jackmu95) [reply src/mixins/dropdown.js]: @tmorehouse Noticed that too. Also tried the `$nextTick()` but it didn't helped.

Comment (tmorehouse) [reply src/mixins/dropdown.js]: Hmmmm... maybe a requestAF instead of nextTick (or a combination of nextTick + requestAF)?

Comment (tmorehouse) [reply src/mixins/dropdown.js]: Something else interesting.... if using tab to navigate the navbar dropdowns, everything works as epected... it is only click on the bottom dropdown toggle (when first dropdown is open) that shows the issue.

Comment (tmorehouse) [reply src/mixins/dropdown.js]: Just trying a delay on the visibility `show` handler to see if that makes a difference...

**Comment by tmorehouse** [comment]
@jackmu95 here is markup that can be used in the playground to repro the issue easily:

```html
<div>
  <b-navbar type="dark" variant="dark">
    <b-navbar-nav class="flex-column">
      <b-nav-item href="#">Home</b-nav-item>
      <!-- Navbar dropdowns -->
      <b-nav-item-dropdown text="Lang" right id="lang-dd" menu-class="position-static">
        <b-dropdown-item href="#">EN</b-dropdown-item>
        <b-dropdown-item href="#">ES</b-dropdown-item>
        <b-dropdown-item href="#">RU</b-dropdown-item>
        <b-dropdown-item href="#">FA</b-dropdown-item>
      </b-nav-item-dropdown>
      <b-nav-item-dropdown text="User" right id="user-dd" menu-class="position-static">
        <b-dropdown-item href="#">Account</b-dropdown-item>
        <b-dropdown-item href="#">Settings</b-dropdown-item>
      </b-nav-item-dropdown>
    </b-navbar-nav>
  </b-navbar>
</div>
```

**Comment by tmorehouse** [comment]
Playground test markup:

```html
<div>
  <b-navbar type="dark" variant="dark" toggleable>
    <b-navbar-nav>
      <b-nav-item href="#">Home</b-nav-item>
      <!-- Navbar dropdowns -->
      <b-nav-item-dropdown text="Lang" right id="lang-dd">
        <b-dropdown-item href="#">EN</b-dropdown-item>
        <b-dropdown-item href="#">ES</b-dropdown-item>
        <b-dropdown-item href="#">RU</b-dropdown-item>
        <b-dropdown-item href="#">FA</b-dropdown-item>
      </b-nav-item-dropdown>
      <b-nav-item-dropdown text="User" right id="user-dd">
        <b-dropdown-item href="#">Account</b-dropdown-item>
        <b-dropdown-item href="#">Settings</b-dropdown-item>
      </b-nav-item-dropdown>
    </b-navbar-nav>
  </b-navbar>
</div>
```

**Comment by tmorehouse** [comment]
Hmmm... works better.. but back to the same issue with keyboard (TAB) navigation not closing the dropdown (if a dropdown toggle is next in the tab sequence)
