### PR TITLE
fix(utils): add back array notation support to `get()` util

### LINKED ISSUE #2680: b-table nested keys in fields prop are not working after update
Hello! 
After upgrading from  2.0.0-rc.10 to ^2.0.0-rc.13 it seems that <b-table> fields prop containing nested keys with array in it is not working anymore.

Before it used to works: 
` fields: [
            { label: 'Name', key: 'some.name' },
            { label: 'Id', key: 'some.id' },
            { label: 'Nested name', key: 'some.group.name' },     
            { label: 'Array name', key: 'array[0].some.name' },
            { label: 'Array Id', key: 'array[0].some.id' },
        ]`
Now the last 2 columns - Array name and Array Id won't be displayed.

And I'll be grateful for some tip how to use fields with such kind of structure.

Thank you!

### PR DESCRIPTION
**Pull request by jackmu95**
## Description of Pull Request:

This PR adds back array notation support to the `get()` util.

Example:
```js
const object = { a: [{ b: { c: 3 } }, 4] }
const result = get(object, 'a[0].b.c') // => 3
```

Closes #2680.

## PR checklist:

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [x] Enhancement to an existing feature
- [ ] ARIA accessibility
- [ ] Documentation update
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact:

**The PR fulfills these requirements:**

- [x] It's submitted to the `dev` branch, **not** the `master` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (i.e.
      `fixes #xxxx[,#xxxx]`, where "xxxx" is the issue number)
- [x] The PR should address only one issue or feature. If adding multiple features or fixing a bug
      and adding a new feature, break them into separate PRs if at all possible.
- [x] PR titles should following the
      [**Conventional Commits**](https://www.conventionalcommits.org/) naming convention (i.e.
      "fix(alert): not alerting during SSR render", "docs(badge): Updated pill examples, fix typos",
      "chore: fix typo in docs", etc). **This is very important, as the `CHANGELOG` is generated
      from these messages.**

**If new features/enhancement/fixes are added or changed:**

- [ ] Includes documentation updates (including updating the component's `package.json` for slot and
      event changes)
- [ ] New/updated tests are included and passing (if required)
- [ ] Existing test suites are passing
- [ ] The changes have not impacted the functionality of other components or directives
- [ ] ARIA Accessibility has been taken into consideration (does it affect screen reader users or
      keyboard only users? clickable items should be in the tab index, etc)

**If adding a new feature, or changing the functionality of an existing feature, the PR's
description above includes:**

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a
      suggestion issue first and wait for approval before working on it)

### CODE REVIEW

File: src/utils/get.js [hunk 1]
```diff
@@ -1,31 +1,27 @@
...
-    return holder
+export default (obj, path, defaultValue = null) => {
+  if (!path || !isObject(obj)) {
+    return defaultValue
   }
 
-  const propParts = (propName + '').split('.')
-  let result = holder
-  let lastPropName
+  path = isArray(path) ? path.join('.') : String(path).replace(/\[(\d+)]/g, '.$1')
```
Comment (tmorehouse) [inline src/utils/get.js]: I would suggest breaking this into two lines:

```js
path = isArray(path) ? path.join('.') : path
path = String(path).replace(/\[(\d+)]/g, '.$1')
```

This would handle array notation in array format, i.e. if path was:
```js
['foo', 'bar[2]', 'baz']
```

File: src/utils/get.js [hunk 2]
```diff
@@ -1,31 +1,27 @@
...
-  ) {
-    if (result[lastPropName] === undefined) return undefined
-    result = result[lastPropName]
+  const steps = path.split('.').filter(Boolean)
+  if (steps.length === 0) {
+    return defaultValue
   }
 
-  return result
+  return steps.every(step => (obj = obj[step]) !== undefined) ? obj : defaultValue
```
Comment (tmorehouse) [inline src/utils/get.js]: When converting the array index to dotted notation, i.e. `foo.bar[2]` becomes `foo.bar.2`, is the `2` treated as a string `"2"` or numeric `2`?

Comment (tmorehouse) [reply src/utils/get.js]: Actually just did a manual test:

```js
a = [1,2,3,4,5]
a[0] // => 1
a['0'] // => 1
a[4] // => 5
a['4'] // => 5
```
numeric and string properties work on arrays and return the same values, so all is good.

Comment (jackmu95) [reply src/utils/get.js]: Yeah, the test would have failed otherwise.
